import Head from 'next/head'
import Banner from '../containers/Banner';
import Footer from '../containers/Footer';
import Header from '../containers/Header';
import SliderContainer from '../containers/SliderContainer';


export default function Home({popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,}) {


    

   
  
  return (
    <div className='max-w-screen '>
      <Head>
        <title>Disney Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header api={process.env.API_KEY}/>
      <Banner/>


      <main className='flex flex-col space-y-12 '>

        <SliderContainer result={popularMovies} title={'Popular Movies'}/>
        <SliderContainer result={popularShows} title={'Popular Shows'}/>
        <SliderContainer result={top_ratedMovies} title={'Top Movies'}/>
        <SliderContainer result={top_ratedShows} title={'Top Shows'}/>
        


        
      </main>
      
      

    </div>
  )
}



  

  export async function getServerSideProps(context) {
    
  
    const [
      popularMoviesRes,
      popularShowsRes,
      top_ratedMoviesRes,
      top_ratedShowsRes,
    ] = await Promise.all([
      fetch(
        `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
      fetch(
        `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
      ),
    ]);
    const [popularMovies, popularShows, top_ratedMovies, top_ratedShows] =
      await Promise.all([
        popularMoviesRes.json(),
        popularShowsRes.json(),
        top_ratedMoviesRes.json(),
        top_ratedShowsRes.json(),
      ]);
      
  
    return {
      props: {
      
        popularMovies: popularMovies.results,
        popularShows: popularShows.results,
        top_ratedMovies: top_ratedMovies.results,
        top_ratedShows: top_ratedShows.results,
      },
    };
}


  
